site_name: Test Documentation
site_author: Yihoo.Kan
repo_url: https://github.com/SerenniaHan/mkdoc-sample
repo_name: mkdoc-sample
copyright: "&copy; 2024 Yihoo.Kan"
site_url: https://serenniahan.github.io/mkdoc-sample/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

extra:
  version:
    provider: mike
    default: latest
  alternate:
    - name: English
      link: /mkdoc-sample/
      lang: en
    - name: 日本語
      link: /mkdoc-sample/ja/
      lang: ja
    - name: 中文(简体)
      link: /mkdoc-sample/zh/
      lang: zh
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

nav:
  - Welcome:
      - index.md

plugins:
  - search:
      lang:
        - en
        - ja
        - zh
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          name: English
          build: true
          default: true
        - locale: ja
          name: 日本語
          build: true
          nav_translations:
            Welcome: ようこそ
        - locale: zh
          name: 中文（简体）
          build: true
          nav_translations:
            Welcome: 欢迎
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null

markdown_extensions:
  - admonition

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
